server:
  port: 8052

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/USER_SERVICE
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
